[project]
name = "swap"
version = "0.1.0"
description = "Experimental face-swap training workspace"
requires-python = ">=3.12,<3.13"
dependencies = [
    "nvidia-dali-cuda130",
    "torch",
    "torchvision",
    "torchcodec",
    "huggingface-hub",
    "numpy",
    "onnx",
    "onnxscript",
    "onnxruntime-gpu",
    "opencv-python",
    "tensorboard",
    "tqdm",
    "segmentation-models-pytorch",
    "fvcore",
    "xformers",
    "torchinfo",
    "ninja",
    "scipy",
    "tensorrt-cu13",
    "httpx[socks]>=0.28.1",
]

[tool.uv]
package = false

[tool.uv.sources]
torch = { index = "pytorch-cu132" }
torchvision = { index = "pytorch-cu132" }
torchcodec = { index = "pytorch-cu132" }
nvidia-dali-cuda130 = { index = "nvidia" }

[[tool.uv.index]]
name = "pytorch-cu132"
url = "https://download.pytorch.org/whl/cu132"
explicit = true

[[tool.uv.index]]
name = "nvidia"
url = "https://pypi.nvidia.com"
explicit = true

[tool.ruff]
line-length = 230
preview = true

[tool.ruff.format]
skip-magic-trailing-comma = false
